//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureFunctions.Extensions.CognitiveServices.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureFunctions.Extensions.CognitiveServices.Tests.Resources.MockResults", typeof(MockResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SamplePhoto {
            get {
                object obj = ResourceManager.GetObject("SamplePhoto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SamplePhotoTooBig {
            get {
                object obj = ResourceManager.GetObject("SamplePhotoTooBig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;tags&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;outdoor&quot;,
        ///      &quot;score&quot;: 0.976
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;bird&quot;,
        ///      &quot;score&quot;: 0.95
        ///    }
        ///  ],
        ///  &quot;description&quot;: {
        ///    &quot;tags&quot;: [
        ///      &quot;outdoor&quot;,
        ///      &quot;bird&quot;
        ///    ],
        ///    &quot;captions&quot;: [
        ///      {
        ///        &quot;text&quot;: &quot;partridge in a pear tree&quot;,
        ///        &quot;confidence&quot;: 0.96
        ///      }
        ///    ]
        ///  }
        ///}.
        /// </summary>
        internal static string VisionAnalysisResults {
            get {
                return ResourceManager.GetString("VisionAnalysisResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;description&quot;: {
        ///    &quot;tags&quot;: [
        ///      &quot;person&quot;,
        ///      &quot;man&quot;,
        ///      &quot;outdoor&quot;,
        ///      &quot;window&quot;,
        ///      &quot;glasses&quot;
        ///    ],
        ///    &quot;captions&quot;: [
        ///      {
        ///        &quot;text&quot;: &quot;Satya Nadella sitting on a bench&quot;,
        ///        &quot;confidence&quot;: 0.48293603002174407
        ///      },
        ///      {
        ///        &quot;text&quot;: &quot;Satya Nadella is sitting on a bench&quot;,
        ///        &quot;confidence&quot;: 0.40037006815422832
        ///      },
        ///      {
        ///        &quot;text&quot;: &quot;Satya Nadella sitting in front of a building&quot;,
        ///        &quot;confidence&quot;: 0.38035155997373377
        ///      }
        ///    ] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VisionDescribeResults {
            get {
                return ResourceManager.GetString("VisionDescribeResults", resourceCulture);
            }
        }
    }
}
